name: Deploy To SMP Server
'on':
  push:
    branches:
      - main
jobs:
  sftp:
    name: "Deploy to SMP Server"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Deploy"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.SFTP_HOSTNAME }}
          remote-port: ${{ secrets.SFTP_HOSTPORT }}
          remote-user: ${{ secrets.SFTP_USERNAME }}
          remote-password: ${{ secrets.SFTP_PASSWORD }}
          remote-path: ${{ secrets.SFTP_REMOTELOC }}
          sync: delta
  api:
    name: "Restart Server"
    needs: sftp
    runs-on: ubuntu-latest
    steps:
      - name: Restart Notice
        run: ${{ secrets.API_RESTARTNOTICE }}
        shell: bash
      - name: Wait for 1 minute
        run: sleep 60s
        shell: bash
      - name: Restart Server
        run: ${{ secrets.API_RESTARTCMD }}
        shell: bash
