name: Restart SMP Server after deploy
'on':
  push:
    branches:
      - main
jobs:
  ci:
    name: "Restart Server"
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
         run: sleep 30s
         shell: bash
      - name: Github Action for curl
        uses: wei/curl@v1.1.1
          with:
            args: ${{ secrets.ARGS }}
